name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write

concurrency: release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v6
        with:
          node-version: '24.20.0'
      - run: >-
          npm install --global semantic-release@25.0.9
          conventional-changelog-conventionalcommits@9.3.1 @semantic-release/git@10.0.1
          semantic-release-replace-plugin@1.2.7
      - run: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
